# Generated by Django 3.0.5 on 2020-04-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_auto_20200419_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='branch',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/static/profile/images/profile_pic.png', null=True, upload_to='profile_pic/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='year',
            field=models.CharField(default='1', max_length=30),
        ),
    ]
