# Generated by Django 3.0.5 on 2020-04-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0005_auto_20200421_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='feedback_filled',
            field=models.CharField(default='', max_length=300),
        ),
    ]
