# Generated by Django 3.0.5 on 2020-04-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0006_userprofile_feedback_filled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='branch',
            field=models.CharField(default='To be updated ', max_length=50),
        ),
    ]
