# Generated by Django 3.0.5 on 2020-04-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0009_auto_20200425_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='category',
        ),
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.CharField(choices=[('Faculty', 'Faculty'), ('Student', 'Student')], default='Student', max_length=10),
        ),
    ]
