# Generated by Django 3.0.5 on 2020-04-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0010_auto_20200425_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='if_faculty_courses_taught',
            field=models.CharField(default='', max_length=300),
        ),
    ]
