# Generated by Django 3.0.5 on 2020-04-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0011_user_if_faculty_courses_taught'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbacktile',
            name='due_data',
        ),
        migrations.AddField(
            model_name='feedbacktile',
            name='due_date',
            field=models.DateField(auto_now=True),
        ),
    ]
