# Generated by Django 3.0.5 on 2020-04-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0013_auto_20200426_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='feedback_filled',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
